### PR TITLE
Social Media Project Milestone2

### PR DESCRIPTION
**Pull request by necmigunduz**
In this project, we did;
- Create Friendship Model and relevant associations,
- Add rspec tests.

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
You made quite a progress in this project. Your `friendships` and `users` are properly modeled. Well done!
However, we need to make some crucial changes before we can merge this PR.
- [x] There's currently no way to send friend request to another user. Please add a button for that. Also remember the same button should be render along side every user on the list of users and on the individual profile page.
- [x] Add a button to reject friendship sent by other users.
- [x] Also make it possible for a user to see friend requests from other users. This is currently not possible
- [ ] Add more unit test cases. Test for validations in the `user` model
- [ ] Add integration tests. Test for a user's ability to send a friend request to another when logged in, a user's ability to confirm friend requests when logged in, etc. Read more about integration testing [here](https://semaphoreci.com/community/tutorials/integration-testing-ruby-on-rails-with-minitest-and-capybara)
- [ ] Fix testing error: `require: cannot load such file -- rspec/core/formatters/progress_formatter (LoadError)`



### Martin Afani

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- [ ] Good job, there is no inline comments in your code :+1: 
- [ ] Good pull request description :100: 

To Improve :factory_worker:

- [ ] Please work on your ` friendships requests `:

As you can see in this gif file, I am not able to send a friend request.

- [ ] Please, extand your test and make sure that all you test cases passed:

In fact, software testing is the process of verifying and validating a software application to check whether it is working as expected. The intent is to find defects and improve product quality. There are two ways to test software, namely Positive Testing, and Negative Testing. It will be perfect if you add test for negative cases.
- [ ] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Comment by saimaAnis21** [comment]
> Changes Required 
> To Highlight: 
> 
> * [ ]  Good job, there is no inline comments in your code +1
> * [ ]  Good pull request description 100
> 
> To Improve 
> 
> * [ ]  Please work on your `friendships requests`:
>   
>   As you can see in this gif file, I am not able to send a friend request.
> * [ ]  Please, extand your test and make sure that all you test cases passed:
>   
>   In fact, software testing is the process of verifying and validating a software application to check whether it is working as expected. The intent is to find defects and improve product quality. There are two ways to test software, namely Positive Testing, and Negative Testing. It will be perfect if you add test for negative cases.
> * [ ]  Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
> 
> That's it, you can submit another code review request after making these changes  
> With all my respect 
> Rindra Josia

**Comment by saimaAnis21** [comment]
Our friendship request is working. The pending requests shows in the current user page. The other user who receives the request can view 'accept' or 'reject'  options when he is signed in.
Capybara is able to find the "Request Friendship" button on our page. The scenario is working successfully at our end.

**Comment by mimipeshy** [comment]
### STATUS: CHANGES REQUIRED 🔴 ♻️ 
Hey there @saimaAnis21 and @necmigunduz 👋🏾 👋🏾 I liked that you tried to implement changes requested by the TSE's. I also appreciate the clarification you made on the PR it was noted. However, before approving this PR check out the comments below

- [ ] When I sign up  a new user and click on the signup button after filling in the form I get the following error, Kindly fix it

image

That's all :smile: kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, or just comment on this PR and tag my name and I will be glad to help_
Regards
Peris Ndanu

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:full_moon:
**Hi team!
Great job so far:clap::clap:.**  

**Major highlights**

- User can invite friends, see friendship request and reject friends
- Posts timeline includes posts written by logged-in user and their friend
- The codebase is clean.

However, we just need to make a few changes to get the milestone approved:muscle:.

**To improve**

- [x] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Currently, it's just a link. Make it a button.

- [ ] The tests only cover the user model. We also need to write tests for comment, friendship, like, and post for the same model. And also do the same for the controller. Both unit and integration test.

Make the above-required changes and when you are ready, request another review.
Kindly drop your questions :point_down: and ping me on slack @ Eric Enaburekhan to respond 
Happy coding:blush:
Eric Enaburekhan

**Review by NtwaliHeritier — APPROVED** [review]
### **STATUS: APPROVED✔✔✔**

Great work implementing the required changes.
You can move to another milestone👍👌👌👍

**Pull request merged**
